In [21]:
def buddy_name(name):
    print("how many maggi",buddy_name)
buddy_name(3)

how many maggi <function buddy_name at 0x0000026FF89E6CF0>


In [34]:
def buddy_name(name="ka style he"):
    print("yeah baburao",name)
buddy_name()

yeah baburao ka style he


In [39]:
def games(name="cricket"):
    print("sports",name)
games("volleyball")
games("kabbadi")
games()

sports volleyball
sports kabbadi
sports cricket


In [41]:
def add(a,b):
    return a+b,a-b,a*b
add(5,6)

(11, -1, 30)

In [50]:
def student(name,age,location,department="cse."):
    print("The name is",name,"age is",age,"location is",location,"depatment",department)
student(name='aryan,',age='20,',location="kudapura,")

The name is aryan, age is 20, location is kudapura, depatment cse.


In [57]:
def animal(*args):
    print("my animal list:",*args)
animal("nayi,","cat,","anaconda,","handi")

my animal list: nayi, cat, anaconda, handi


In [18]:
import numpy as np
a=np.array([[10,20,30,40,50],[21,31,42,53,62]])
b=np.array([[100,60,70,80,90],[53,62,83,94,71]])
print(type(a))
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a%b)
print(a/b)
print(np.array(a))
print(a.shape)
print(np.array(a).dtype)

<class 'numpy.ndarray'>
[[10 20 30 40 50]
 [21 31 42 53 62]]
[[100  60  70  80  90]
 [ 53  62  83  94  71]]
[[110  80 100 120 140]
 [ 74  93 125 147 133]]
[[-90 -40 -40 -40 -40]
 [-32 -31 -41 -41  -9]]
[[1000 1200 2100 3200 4500]
 [1113 1922 3486 4982 4402]]
[[10 20 30 40 50]
 [21 31 42 53 62]]
[[0.1        0.33333333 0.42857143 0.5        0.55555556]
 [0.39622642 0.5        0.5060241  0.56382979 0.87323944]]
[[10 20 30 40 50]
 [21 31 42 53 62]]
(2, 5)
int64


In [6]:
a=1
print(type(a))
print(a)

<class 'int'>
1


In [36]:
import numpy as np
a=np.array([[10,20,30,40,50],[21,31,42,53,62],[43,54,76,93,96]])
b=np.array([[100,60,70,80,90],[53,62,83,94,71],[73,84,95,82,90]])
print(np.array(a+b))
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(a & b)
print(a[(a>20)&(a>40)])

[[110  80 100 120 140]
 [ 74  93 125 147 133]
 [116 138 171 175 186]]
721
10
96
48.06666666666667
[[ 0 20  6  0 18]
 [21 30  2 20  6]
 [ 9 20 76 80 64]]
[50 42 53 62 43 54 76 93 96]


In [45]:
import numpy as np
a=np.array([[10,20,30,40,50],[21,31,42,53,62],[43,54,76,93,96]])
b=np.array([[100,60,70,80,90],[53,62,83,94,71],[73,84,95,82,90]])
print(np.sum(a,axis=0))
print(np.sum(b,axis=1))
print(np.min(a,axis=0))
print(np.max(a,axis=0))


[ 74 105 148 186 208]
[400 363 424]
[10 20 30 40 50]
[43 54 76 93 96]


AttributeError: module 'numpy' has no attribute 'matmal'

In [47]:
import numpy as np
a=np.array([[10,20],[30,40]])
b=np.array([[50,60],[70,80]])
print(np.matmul(a,b))

[[1900 2200]
 [4300 5000]]
